Fix scoresheet, scoresheets, and scoresheet entries
matthaws/douze-points pull request #14
Opened 2018-02-20 17:23 UTC by Bhammy

Scoresheets.jsx now correctly updates on a receiveScoresheet action; this cascades down so that score entries correctly update.

2018-02-20 22:41 UTC, Bhammy commented
Newest branch calls fetchContests on componentDidMount for new scoresheet form so as to fill dropdown.

2018-02-21 22:16 UTC, matthaws requested changes
Remove debugger and extraneous mapStateToProps

2018-02-21 22:16 UTC, matthaws commented on src/components/scoresheets/new_scoresheet.jsx
> +    debugger
debugger?

2018-02-21 22:16 UTC, matthaws commented on src/components/scoresheets/scoresheet_entry.jsx
> +// mapXToProps
?

2018-02-21 22:16 UTC, matthaws commented on src/components/scoresheets/scoresheet_entry.jsx
> +const mapStateToProps = (state, ownProps) => ({
if mapStateToProps is not being used, let's remove it and pass null in as the first argument to connect

2018-02-23 15:11 UTC, matthaws approved these changes

2018-02-23 15:11 UTC, merged