Ian contests
matthaws/douze-points pull request #4
Opened 2018-02-10 20:45 UTC by LlanddewiLovesYou

Yeah so, I wrote this code so you should probably look at it because, yknow... it will need it.

2018-02-10 22:13 UTC, Bhammy requested changes
Looks good to me! Two minor questions/comments.

2018-02-10 22:13 UTC, Bhammy commented on src/components/app.jsx
> +    fetchCurrentUser: PropTypes.func.isRequired
Is this supposed to be fetchContest?

2018-02-10 22:13 UTC, Bhammy commented on src/index.js
> +window.fetchContest = fetchContest
is this for testing purposes? otherwise we don't need this on the window in the production version, I think.

2018-02-10 23:33 UTC, LlanddewiLovesYou commented
Wha? And yes.

On Feb 10, 2018 5:13 PM, "Brendan Hamill" <notifications@github.com> wrote:

> *@Bhammy* requested changes on this pull request.
>
> Looks good to me! Two minor questions/comments.
> ------------------------------
>
> In src/components/app.jsx
> <https://github.com/matthaws/douze-points/pull/4#discussion_r167412542>:
>
> > @@ -11,7 +11,8 @@ import "./App.css";
>
>  class App extends Component {
>    static propTypes = {
> -    authenticateUser: PropTypes.func.isRequired
> +    authenticateUser: PropTypes.func.isRequired,
> +    fetchCurrentUser: PropTypes.func.isRequired
>
> Is this supposed to be fetchContest?
> ------------------------------
>
> In src/index.js
> <https://github.com/matthaws/douze-points/pull/4#discussion_r167412561>:
>
> > @@ -14,4 +15,6 @@ ReactDOM.render(
>    document.getElementById("root")
>  );
>
> +window.fetchContest = fetchContest
>
> is this for testing purposes? otherwise we don't need this on the window
> in the production version, I think.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matthaws/douze-points/pull/4#pullrequestreview-95634880>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AckZx684XHT-l-jXEY954OhELFguUcXBks5tThSCgaJpZM4SBEvJ>
> .
>

2018-02-10 23:56 UTC, Bhammy commented
Not sure which of your responses goes to which of my comments - if it's in order, I'm wondering if fetchCurrentUser is supposed to be fetchContest because authenticateUser already calls receiveCurrentUser on the backend. For the other, yeah, just remove the window.fetchContest for the version to merge with the master branch.

2018-02-11 00:27 UTC, LlanddewiLovesYou commented
It was in order, yes. I don't know. I didn't write anything having to do
with users. That's some weird merge stuff


On Feb 10, 2018 6:56 PM, "Brendan Hamill" <notifications@github.com> wrote:

> Not sure which of your responses goes to which of my comments - if it's in
> order, I'm wondering if fetchCurrentUser is supposed to be fetchContest
> because authenticateUser already calls receiveCurrentUser on the backend.
> For the other, yeah, just remove the window.fetchContest for the version to
> merge with the master branch.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matthaws/douze-points/pull/4#issuecomment-364706182>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AckZx3kmwU4sn4dVZT_jDZsBm4K77GPFks5tTiypgaJpZM4SBEvJ>
> .
>

2018-02-11 00:53 UTC, Bhammy commented
Okay, that's fine. Just make the changes locally (delete the window.fetchContest and the fetchCurrentUser) and commit again and I can approve. Thanks! :)

2018-02-12 00:23 UTC, matthaws commented
So the fetchCurrentUser thing is not a mistake, its on the App component to get the current user data if it detects the auth token stored locally. Check out our recent other additions!

2018-02-12 01:52 UTC, Bhammy approved these changes

2018-02-12 01:52 UTC, merged